configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore

# package Web Application project for Web Deploy
build:
  verbosity: minimal
  
artifacts: 
  - path: NugetBuild\*.nupkg
    name: package
  
deploy:
  provider: NuGet
  api_key:
    secure: 60GlR7nN1YaHqUTl5qKsfCMxizs+rz213RufDAGKY2mJFE9nm81HZpBR2MrPHZCT
  artifact: package
